version: '3'
  
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "80:80/tcp"
    environment:
    - 'TZ=America/Los_Angeles'
    - 'WEBPASSWORD=<insert password>'
    - 'DNS1=8.8.8.8'
    - 'DNS2=no'
    volumes:
    - './etc-pihole:/etc/pihole'
    - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
